export const names = [
  'Molly',
  'Charlie',
  'Tigger',
  'Poppy',
  'Oscar',
  'Smudge',
  'Millie',
  'Daisy',
  'Max',
  'Jasper',
  'Felix',
  'Minka',
  'Moritz',
  'Charly',
  'Tiger (tee-gher)',
  'Eve',
  'Susi',
  'Lisa',
  'Blacky',
  'Muschi',
  'Romeo',
  'Pallina (Small ball)',
  'Micio (Pussycat)',
  'Luna (Moon)',
  'Chicco (Grain)',
  'Birba (Scoundrel)',
  'Trilly',
  'Leo',
  'Minù',
  'Briciola( Crumb )',
  'Minou',
  'Grisou',
  'Ti-Mine',
  'Félix',
  'Caramel',
  'Mimi',
  'Pacha',
  'Charlotte',
  'Minette',
  'Chanel',
  'Kariri',
  'Momo (Peach)',
  'Kuro (Black)',
  'Hana (Flower)',
  'Koko (Here)',
  'Shiro (White)',
  'Sora (Sky)',
  'Fuku (Lucky)',
  'Mei',
  'Kai (Seashell)',
  'Chiro',
  'Chibi (Tiny)',
  'Mikan (Mandarin Orange)',
  'Kotetsu (Small Iron)',
  'Sakura (Cherry Blossom)',
  'Tora (Tiger)',
  'Maron (Chestnut)',
  'Rin (Graceful)',
  'Azuki (Sweet Red Beans)',
  'Jiji',
  'Hime (Princess)',
  'Maru (Circle)',
  'Tama (Pearl or Marble)',
  'Moka (Mocha)',
  'Leo',
  'Kinako',
  'Kurumi (Walnut)',
  'Chobi',
  'Haru (Spring)',
  'Miruku (Milk)',
  'Minto (Mint)',
  'Yuki( Snow )',
];
